version: '3'
services:

  web:
    build: .
    ports:
     - "8000:8000"
    environment:
      ELASTICSEARCH_HOSTS: elasticsearch:9200
      REDIS_HOST: redis:6379
      REDIS_PASSWORD: IsecScan
    depends_on:
      - redis
      - elasticsearch
  redis:
    image: redis:5.0.3-stretch
    command: redis-server --requirepass IsecScan
    restart: always
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:5.6-alpine
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    expose:
      - "9200"